# Generated by Django 4.0.4 on 2022-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
