# Generated by Django 4.0.4 on 2022-05-10 11:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
