# Generated by Django 4.0.4 on 2022-06-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carrito_mods_product_user_direccion_user_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
