# Generated by Django 4.0.4 on 2022-06-18 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_mods_user_mods_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mods',
            name='user',
        ),
        migrations.AddField(
            model_name='mods',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
